### ISSUE TITLE
Failed to build release for Android devices. No issue on iOS devices.

### ISSUE THREAD

**Issue by zinwalin** [aaronoe/FlutterCinematic#17]
RMBP➜  FlutterCinematic git:(master) ✗  >flutter run -d all --release
Running "flutter packages get" in FlutterCinematic...        0.5s
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.8s
Launching lib/main.dart on MI 6 in release mode...
Running 'gradlew assembleRelease'...
VMIsolate(CodeSize): 4613
Isolate(CodeSize): 1699574
ReadOnlyData(CodeSize): 2484048
Instructions(CodeSize): 5880224
Total(CodeSize): 10068459
Gradle build failed to produce an Android package.

**Comment by zinwalin** [comment]
verbose:


[ +419 ms] "flutter run" took 9,906ms.
Gradle build failed to produce an Android package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:408)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:318)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:36)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:377)
<asynchronous suspension>
#5      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:349)
<asynchronous suspension>
#6      ColdRunner.run (package:flutter_tools/src/run_cold.dart:54)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///Users/michael/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by amit-bhandari** [comment]
I faced the same issue. 

I was able to successfully create debug package by giving 'flutter build apk --debug'

For creating release build, I created key.jks (followed this doc https://flutter.io/android-release/ ) and voilla, got the release apk.
