### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by UnluckyY1** [aaronoe/FlutterCinematic#23]
Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rxdart-0.16.7/lib/src/observable.dart:1826:57: Error: The method 'retype' isn't defined for the class 'Stream<T>'.
 - 'Stream' is from 'dart:async'.

**Comment by azri92** [comment]
You need to modify `pubspec.yaml` & change the version for `rxdart` to `0.18.0`.

Answer from https://github.com/ReactiveX/rxdart/issues/160
