### ISSUE TITLE
Favorite menu and adding to list icon missing

### ISSUE THREAD

**Issue by sarada** [aaronoe/FlutterCinematic#5]
Hi, when I compare with Java version cinematic app, I saw the favorite option is missing in flutter app. Please enhance to provide such.
Thanks.

**Comment by aaronoe** [comment]
Hi @sarada 
I implemented the favorite functionality now. As of now it just stores the favorites in `SharedPreferences` but I am planing to move that to a database, after evaluating my options :smile:
